#!/usr/bin/env node

/**
 * Auto-generate audioAssets.ts from assets/audio directory
 * This ensures all audio files are properly bundled in React Native
 */

const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, '../assets/audio');
const OUTPUT_FILE = path.join(__dirname, '../utils/audioAssets.ts');

// Recursively find all audio files
const findAudioFiles = (dir, baseDir = dir) => {
  const files = [];
  const items = fs.readdirSync(dir);
  
  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);
    
    if (stat.isDirectory()) {
      files.push(...findAudioFiles(fullPath, baseDir));
    } else if (item.endsWith('.aiff') || item.endsWith('.mp3') || item.endsWith('.wav')) {
      const relativePath = path.relative(baseDir, fullPath);
      files.push(relativePath);
    }
  }
  
  return files;
};

const main = () => {
  console.log('🔄 Updating audioAssets.ts...\n');
  
  const audioFiles = findAudioFiles(AUDIO_DIR);
  audioFiles.sort();
  
  console.log(`📁 Found ${audioFiles.length} audio files\n`);
  
  const content = `/**
 * Audio Assets Manifest
 * Auto-generated by scripts/updateAudioAssets.js
 * 
 * This file ensures all audio files are properly bundled in React Native.
 * Run: npm run update-audio-assets to regenerate this file.
 */

export const AUDIO_ASSETS: Record<string, any> = {
${audioFiles.map(file => {
  const key = file.replace(/\\/g, '/');
  const requirePath = `../assets/audio/${key}`;
  return `  '${key}': require('${requirePath}'),`;
}).join('\n')}
};

export const getAudioAsset = (audioPath: string): any => {
  if (!audioPath) return null;
  
  // Normalize path (remove leading slash if any)
  const normalizedPath = audioPath.replace(/^\\//, '');
  
  const asset = AUDIO_ASSETS[normalizedPath];
  if (!asset) {
    console.warn(\`[AudioAssets] File not found: \${normalizedPath}\`);
  }
  return asset;
};

export const hasAudioAsset = (audioPath: string): boolean => {
  if (!audioPath) return false;
  const normalizedPath = audioPath.replace(/^\\//, '');
  return normalizedPath in AUDIO_ASSETS;
};

export const getAllAudioPaths = (): string[] => {
  return Object.keys(AUDIO_ASSETS);
};

console.log('[AudioAssets] Loaded ${audioFiles.length} audio files');
`;
  
  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  
  console.log('✅ audioAssets.ts updated successfully!');
  console.log(`📊 ${audioFiles.length} audio files registered\n`);
  console.log('Sample entries:');
  audioFiles.slice(0, 5).forEach(file => {
    console.log(`  - ${file}`);
  });
  if (audioFiles.length > 5) {
    console.log(`  ... and ${audioFiles.length - 5} more`);
  }
};

main();
